<#
.SYNOPSIS
    Heirvo Smoke-Test Kit -- Content Generator
    Generates burnable test payloads into testkit\content\ and records SHA-256 hashes.

.DESCRIPTION
    Produces real files (not stubs) using the bundled ffmpeg and ImageMagick so the
    maker can burn them to blank DVDs/CDs and then run Heirvo against them.
    Run from ANY directory -- all paths are absolute.

.NOTES
    Author  : We Get Found LLC / Heirvo Labs
    Version : 1.0.0 (2026-06-04)
    Requires: ffmpeg.exe + ffprobe.exe (bundled), ImageMagick magick.exe (bundled),
              Windows SAPI (built-in), Python 3.12 (for manifest JSON).
#>

[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ---------------------------------------------------------------------------
# Absolute paths
# ---------------------------------------------------------------------------
$HEIRVO_ROOT = "D:\WeGetFound\brands\heirvo"
$TESTKIT     = "$HEIRVO_ROOT\testkit"
$CONTENT     = "$TESTKIT\content"
$FFMPEG      = "$HEIRVO_ROOT\src-tauri\resources\ffmpeg\ffmpeg.exe"
$FFPROBE     = "$HEIRVO_ROOT\src-tauri\resources\ffmpeg\ffprobe.exe"
$MAGICK      = "C:\Users\Lenovo\AppData\Roaming\com.heirvo.app\imagemagick\magick.exe"

# ---------------------------------------------------------------------------
# Colour helpers
# ---------------------------------------------------------------------------
function Write-Header { param([string]$msg) Write-Host "`n==> $msg" -ForegroundColor Cyan }
function Write-OK     { param([string]$msg) Write-Host "    [OK] $msg" -ForegroundColor Green }
function Write-WARN   { param([string]$msg) Write-Host "    [WARN] $msg" -ForegroundColor Yellow }
function Write-ERR    { param([string]$msg) Write-Host "    [ERR] $msg" -ForegroundColor Red }
function Write-Step   { param([string]$msg) Write-Host "    --> $msg" -ForegroundColor Gray }

# ---------------------------------------------------------------------------
# Tool guard
# ---------------------------------------------------------------------------
function Require-Tool { param([string]$path, [string]$name)
    if (-not (Test-Path $path)) {
        Write-ERR "$name not found at: $path"
        Write-ERR "Cannot continue. Check HEIRVO_ROOT in this script."
        exit 1
    }
    Write-Step "Found $name"
}

Write-Header "Checking tools"
Require-Tool $FFMPEG  "ffmpeg"
Require-Tool $FFPROBE "ffprobe"

$HaveMagick = Test-Path $MAGICK
if ($HaveMagick) {
    Write-Step "Found ImageMagick (magick.exe)"
} else {
    Write-WARN "ImageMagick not found at: $MAGICK"
    Write-WARN "Will use ffmpeg lavfi for images (no HEIC generation possible)"
}

# ---------------------------------------------------------------------------
# Directory setup
# ---------------------------------------------------------------------------
Write-Header "Creating output directories"

foreach ($d in @(
    "$CONTENT\data-disc",
    "$CONTENT\photos",
    "$CONTENT\spoken-word",
    "$CONTENT\video-ts-source"
)) {
    New-Item -ItemType Directory -Force $d | Out-Null
    Write-Step $d
}

# ---------------------------------------------------------------------------
# Utility: run a command and assert success.
# Spawns a helper PowerShell script so that:
#   (a) argument strings containing newlines are passed intact (no splitting)
#   (b) stderr is captured via RedirectStandardError without PS ErrorRecord wrapping
# ---------------------------------------------------------------------------
function Run-Cmd {
    param([string]$exe, [string[]]$argList, [string]$description)
    Write-Step "Running: $description"

    $uid          = [System.IO.Path]::GetRandomFileName().Replace(".","")
    $helperScript = "$env:TEMP\heirvo_run_$uid.ps1"
    $stderrFile   = "$env:TEMP\heirvo_run_${uid}_stderr.txt"

    # Build an array literal inside the helper (no trailing comma on last element).
    $escapedExe = $exe.Replace("'","''")
    $innerLines = for ($i = 0; $i -lt $argList.Count; $i++) {
        $a = $argList[$i].Replace("'","''")
        if ($i -lt ($argList.Count - 1)) { "  '$a'," } else { "  '$a'" }
    }
    $helperContent = "# auto-generated by Heirvo testkit`r`n"
    $helperContent += "`$argz = @(`r`n$($innerLines -join "`r`n")`r`n)`r`n"
    $helperContent += "& '$escapedExe' @argz`r`n"
    $helperContent += "exit `$LASTEXITCODE`r`n"
    [System.IO.File]::WriteAllText($helperScript, $helperContent, [System.Text.Encoding]::Unicode)

    $proc = Start-Process -FilePath "powershell.exe" `
        -ArgumentList "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-File", "`"$helperScript`"" `
        -NoNewWindow -Wait -PassThru `
        -RedirectStandardError $stderrFile

    Remove-Item $helperScript -ErrorAction SilentlyContinue

    if ($proc.ExitCode -ne 0) {
        $stderr = ""
        if (Test-Path $stderrFile) {
            $stderr = (Get-Content $stderrFile -Raw -ErrorAction SilentlyContinue).Trim()
        }
        Remove-Item $stderrFile -ErrorAction SilentlyContinue
        Write-ERR "Command failed (exit $($proc.ExitCode)): $description"
        if ($stderr) { Write-ERR "stderr: $stderr" }
        throw "Command failed: $description"
    }
    Remove-Item $stderrFile -ErrorAction SilentlyContinue
}

# ---------------------------------------------------------------------------
# SHA-256 manifest accumulator
# ---------------------------------------------------------------------------
$ManifestEntries = [System.Collections.Generic.List[object]]::new()

function Record-Hash {
    param([string]$filePath, [string]$label = "")
    $rel  = $filePath.Replace($CONTENT, "").TrimStart("\")
    $hash = (Get-FileHash $filePath -Algorithm SHA256).Hash
    $sz   = (Get-Item $filePath).Length
    $ManifestEntries.Add([PSCustomObject]@{
        path   = $rel
        sha256 = $hash
        size   = $sz
        label  = $label
    })
    $kb = [math]::Round($sz / 1024, 1)
    Write-OK "$rel  [$kb KB]  SHA256:$($hash.Substring(0,16))..."
}

# ---------------------------------------------------------------------------
# Image-generation helper (ImageMagick or ffmpeg fallback)
# ---------------------------------------------------------------------------
function Make-Image {
    param(
        [string]$outPath,
        [string]$label,
        [int]$w = 640,
        [int]$h = 480
    )

    if ($HaveMagick) {
        # Use Arial (always available on Windows).
        # ImageMagick -annotate requires an actual newline char (not literal \n).
        $nl = [char]10
        $annotateText = "Heirvo Test${nl}$label"
        Run-Cmd $MAGICK @(
            "-size", "${w}x${h}",
            "gradient:navy-steelblue",
            "-gravity", "Center",
            "-fill", "white",
            "-font", "Arial",
            "-pointsize", "28",
            "-annotate", "0", $annotateText,
            $outPath
        ) "ImageMagick: $label -> $([System.IO.Path]::GetFileName($outPath))"
    } else {
        # ffmpeg lavfi: generate a static color frame and save as image
        $tmpPng = "$env:TEMP\heirvo_testcard_tmp.png"
        Run-Cmd $FFMPEG @(
            "-y", "-f", "lavfi",
            "-i", "color=c=0x00008B:size=${w}x${h}:rate=1:duration=1",
            "-vf", "drawtext=text='Heirvo Test':fontcolor=white:fontsize=36:x=(w-text_w)/2:y=(h-text_h)/2",
            "-frames:v", "1",
            $tmpPng
        ) "ffmpeg lavfi: temp PNG for $label"

        $ext = [System.IO.Path]::GetExtension($outPath).TrimStart(".")
        if ($ext -eq "png") {
            Copy-Item $tmpPng $outPath -Force
        } elseif ($ext -in @("jpg","jpeg","bmp","tiff","gif","webp")) {
            Run-Cmd $FFMPEG @("-y", "-i", $tmpPng, $outPath) "ffmpeg: PNG -> $ext"
        } else {
            Copy-Item $tmpPng $outPath -Force
        }
    }
}

# ---------------------------------------------------------------------------
# Part 1 -- data-disc
# ---------------------------------------------------------------------------
Write-Header "Part 1 -- data-disc (mixed files)"

# 1a. MP4: testsrc video + 440 Hz sine audio, 10 seconds
$dataMP4 = "$CONTENT\data-disc\test-video.mp4"
Run-Cmd $FFMPEG @(
    "-y",
    "-f", "lavfi", "-i", "testsrc=duration=10:size=640x480:rate=25",
    "-f", "lavfi", "-i", "sine=frequency=440:duration=10",
    "-c:v", "libx264", "-preset", "fast", "-crf", "28",
    "-c:a", "aac", "-b:a", "96k",
    "-t", "10",
    $dataMP4
) "Generating test-video.mp4 (testsrc + 440 Hz sine, 10 s)"
Record-Hash $dataMP4

# 1b. Image test cards in each format
$imageFormats = @(
    @{ ext = "jpg";  label = "JPEG test card"  },
    @{ ext = "png";  label = "PNG test card"   },
    @{ ext = "gif";  label = "GIF test card"   },
    @{ ext = "bmp";  label = "BMP test card"   },
    @{ ext = "tiff"; label = "TIFF test card"  },
    @{ ext = "webp"; label = "WebP test card"  }
)

foreach ($fmt in $imageFormats) {
    $outFile = "$CONTENT\data-disc\testcard.$($fmt.ext)"
    Make-Image $outFile $fmt.label 640 480
    Record-Hash $outFile
}

# 1c. PDF -- ImageMagick converts PNG to PDF; fallback is a hand-crafted minimal PDF
$pdfPath = "$CONTENT\data-disc\test-document.pdf"
if ($HaveMagick) {
    Run-Cmd $MAGICK @(
        "-density", "72",
        "$CONTENT\data-disc\testcard.png",
        $pdfPath
    ) "ImageMagick: PNG to PDF"
} else {
    # Minimal but valid PDF (single page, embedded text)
    $pdfBytes = [System.Text.Encoding]::ASCII.GetBytes(@"
%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 595 842]/Contents 4 0 R/Resources<</Font<</F1 5 0 R>>>>>>endobj
4 0 obj<</Length 72>>
stream
BT /F1 24 Tf 160 700 Td (Heirvo Test Document) Tj 160 660 Td (smoke-test kit) Tj ET
endstream
endobj
5 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj
xref
0 6
0000000000 65535 f
0000000009 00000 n
0000000058 00000 n
0000000115 00000 n
0000000270 00000 n
0000000394 00000 n
trailer<</Size 6/Root 1 0 R>>
startxref
472
%%EOF
"@)
    [System.IO.File]::WriteAllBytes($pdfPath, $pdfBytes)
    Write-Step "Wrote hand-crafted minimal PDF"
}
Record-Hash $pdfPath

# 1d. readme.txt
$readmePath = "$CONTENT\data-disc\readme.txt"
$readmeContent = "Heirvo Smoke-Test Kit -- Data Disc`r`n"
$readmeContent += "Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')`r`n`r`n"
$readmeContent += "Contents:`r`n"
$readmeContent += "  test-video.mp4     - 10-second MP4 (testsrc + 440 Hz sine audio)`r`n"
$readmeContent += "  testcard.jpg       - JPEG test image`r`n"
$readmeContent += "  testcard.png       - PNG test image`r`n"
$readmeContent += "  testcard.gif       - GIF test image`r`n"
$readmeContent += "  testcard.bmp       - BMP test image`r`n"
$readmeContent += "  testcard.tiff      - TIFF test image`r`n"
$readmeContent += "  testcard.webp      - WebP test image`r`n"
$readmeContent += "  test-document.pdf  - Single-page PDF`r`n`r`n"
$readmeContent += "Burn as a DATA DISC (ISO9660 or Joliet) using ImgBurn.`r`n"
$readmeContent += "ImgBurn: Mode > Write Files/Folders to Disc, add this folder, burn.`r`n"
[System.IO.File]::WriteAllText($readmePath, $readmeContent, [System.Text.Encoding]::UTF8)
Record-Hash $readmePath

# ---------------------------------------------------------------------------
# Part 2 -- photos (higher-res for gallery + thumbnail + convert tests)
# ---------------------------------------------------------------------------
Write-Header "Part 2 -- photos (1600x1200, gallery + thumbnail test)"

foreach ($fmt in $imageFormats) {
    $outFile = "$CONTENT\photos\photo.$($fmt.ext)"
    Make-Image $outFile "$($fmt.label) 1600x1200" 1600 1200
    Record-Hash $outFile
}

# HEIC: attempt via ImageMagick (requires libheif build); gracefully skip if unsupported
$heicPath      = "$CONTENT\photos\photo.heic"
$heicGenerated = $false
if ($HaveMagick) {
    try {
        $nl2 = [char]10
        Run-Cmd $MAGICK @(
            "-size", "1600x1200",
            "gradient:darkgreen-teal",
            "-gravity", "Center",
            "-fill", "white",
            "-font", "Arial",
            "-pointsize", "48",
            "-annotate", "0", "Heirvo Test${nl2}HEIC photo.heic",
            $heicPath
        ) "ImageMagick: HEIC generation attempt"
        if (Test-Path $heicPath) {
            $heicGenerated = $true
            Record-Hash $heicPath
        }
    } catch {
        Write-WARN "HEIC generation failed (ImageMagick likely lacks libheif): $_"
        Write-WARN "HEIC workaround: AirDrop any iPhone photo into testkit\content\photos\"
        "HEIC file must be supplied manually -- ImageMagick build lacks libheif.`r`nAirDrop any .heic from an iPhone into this folder." |
            Set-Content "$CONTENT\photos\HEIC-MISSING.txt" -Encoding UTF8
    }
}
if (-not $heicGenerated) {
    Write-WARN "HEIC NOT generated -- see photos\HEIC-MISSING.txt for workaround"
}

# ---------------------------------------------------------------------------
# Part 3 -- spoken-word MP4 (SAPI synthesis -> ffmpeg mux)
# ---------------------------------------------------------------------------
Write-Header "Part 3 -- spoken-word MP4 (SAPI -> WAV -> ffmpeg mux)"

# These words must appear in the Whisper transcript for the test to PASS
$TARGET_WORDS = @("birthday", "Hawaii", "grandmother", "nineteen", "summer", "photograph", "memory")

# Save the spoken script so the verifier knows what to search for
$scriptPath = "$CONTENT\spoken-word\script.txt"
$spokenScript  = "It was a warm summer in nineteen ninety-eight when grandmother turned seventy. "
$spokenScript += "We flew to Hawaii for her birthday, a trip none of us will ever forget. "
$spokenScript += "She stood on the beach holding a photograph of the whole family, "
$spokenScript += "and said it was her favourite memory in the whole world. "
$spokenScript += "That moment, preserved forever, is exactly what Heirvo was made for."
[System.IO.File]::WriteAllText($scriptPath, $spokenScript, [System.Text.Encoding]::UTF8)
Write-Step "Saved spoken script to script.txt"

# Synthesize via Windows SAPI (System.Speech.Synthesis.SpeechSynthesizer)
$wavPath = "$CONTENT\spoken-word\speech.wav"

# Write a tiny helper script to a temp file to avoid quoting issues
$sapiHelper = "$env:TEMP\heirvo_sapi_synth.ps1"
$sapiScriptContent  = "Add-Type -AssemblyName System.Speech`r`n"
$sapiScriptContent += "`$synth = New-Object System.Speech.Synthesis.SpeechSynthesizer`r`n"
$sapiScriptContent += "`$synth.Rate = -2`r`n"
$sapiScriptContent += "`$synth.Volume = 100`r`n"
$sapiScriptContent += "`$synth.SetOutputToWaveFile('$wavPath')`r`n"
$sapiScriptContent += "`$synth.Speak(@'`r`n$spokenScript`r`n'@)`r`n"
$sapiScriptContent += "`$synth.SetOutputToDefaultAudioDevice()`r`n"
$sapiScriptContent += "`$synth.Dispose()`r`n"
$sapiScriptContent += "Write-Host 'SAPI synthesis complete'`r`n"
[System.IO.File]::WriteAllText($sapiHelper, $sapiScriptContent, [System.Text.Encoding]::Unicode)

Write-Step "Synthesizing speech via Windows SAPI..."
$sapiResult = powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $sapiHelper 2>&1
Write-Step "SAPI output: $sapiResult"

if (-not (Test-Path $wavPath)) {
    Write-ERR "SAPI synthesis failed -- WAV not produced at: $wavPath"
    Write-ERR "Ensure you are running on Windows with System.Speech installed."
    exit 1
}

$wavKB = [math]::Round((Get-Item $wavPath).Length / 1024, 1)
Write-OK "speech.wav generated ($wavKB KB)"
Record-Hash $wavPath

# Detect WAV duration via ffprobe
$rawDur = & $FFPROBE -v error -show_entries format=duration `
    -of default=noprint_wrappers=1:nokey=1 $wavPath 2>&1
$wavDuration = 0.0
try { $wavDuration = [double]($rawDur | Select-Object -Last 1) } catch {}
Write-Step ("WAV duration: {0:F1} seconds" -f $wavDuration)

# Mux WAV + a dark color background into spoken.mp4
$spokenMP4 = "$CONTENT\spoken-word\spoken.mp4"
Run-Cmd $FFMPEG @(
    "-y",
    "-f", "lavfi", "-i", "color=c=0x1a1a2e:size=640x480:rate=25",
    "-i", $wavPath,
    "-vf", "drawtext=text='Heirvo Spoken-Word Test':fontcolor=white:fontsize=28:x=(w-text_w)/2:y=(h-text_h)/2",
    "-c:v", "libx264", "-preset", "fast", "-crf", "28",
    "-c:a", "aac", "-b:a", "128k",
    "-shortest",
    $spokenMP4
) "Muxing speech.wav + visual -> spoken.mp4"
Record-Hash $spokenMP4
Record-Hash $scriptPath

# ---------------------------------------------------------------------------
# Part 4 -- video-ts-source (source MP4 + authoring guide)
# ---------------------------------------------------------------------------
Write-Header "Part 4 -- video-ts-source (source clip + authoring instructions)"

$vtsSource = "$CONTENT\video-ts-source\source-clip.mp4"
Copy-Item $dataMP4 $vtsSource -Force
Record-Hash $vtsSource

$howToLines = @(
    "HOW TO AUTHOR A DVD-VIDEO (VIDEO_TS) AND BURN IT",
    "=================================================",
    "Required: DVDStyler (free, dvdstyler.org) + ImgBurn (already installed)",
    "",
    "Step 1 -- Author VIDEO_TS with DVDStyler:",
    "  a. Open DVDStyler > New Project > NTSC (or PAL for European)",
    "  b. Drag source-clip.mp4 onto the title area",
    "  c. File > Burn > tick 'just generate' to output VIDEO_TS to disk",
    "     Output folder: C:\Temp\dvdvideo\",
    "  This produces:",
    "    VIDEO_TS\VIDEO_TS.IFO",
    "    VIDEO_TS\VIDEO_TS.BUP",
    "    VIDEO_TS\VTS_01_0.IFO",
    "    VIDEO_TS\VTS_01_0.BUP",
    "    VIDEO_TS\VTS_01_1.VOB",
    "",
    "Step 2 -- Burn DVD-Video with ImgBurn:",
    "  a. ImgBurn > Mode > Write Files/Folders to Disc",
    "  b. Source: select C:\Temp\dvdvideo\ (parent of VIDEO_TS folder)",
    "  c. File System: UDF/ISO9660   Volume Label: HEIRVO_TEST_DVD",
    "  d. Insert blank DVD-R, click the burn button",
    "",
    "Step 3 -- Verify:",
    "  Eject and re-insert. Windows should show VIDEO_TS folder on the disc.",
    "",
    "What Heirvo tests:",
    "  * IFO path parsing and VOB structure detection",
    "  * Save as MP4 transcode of the VOB stream",
    "  * Duration detection and library entry creation",
    "",
    "Fallback if DVDStyler is unavailable:",
    "  Burn source-clip.mp4 as a plain DATA disc instead (see data-disc readme.txt).",
    "  Record result in the matrix as 'DATA DVD substitute' not 'DVD-Video'.",
    "",
    "Note: true DVD-Video authoring cannot be fully scripted -- a GUI DVD tool",
    "is required for the VIDEO_TS structure. This script provides the source MP4 only."
)
[System.IO.File]::WriteAllLines(
    "$CONTENT\video-ts-source\HOW-TO-AUTHOR.txt",
    $howToLines,
    [System.Text.Encoding]::UTF8
)
Record-Hash "$CONTENT\video-ts-source\HOW-TO-AUTHOR.txt"

# ---------------------------------------------------------------------------
# Part 5 -- manifest.json
# ---------------------------------------------------------------------------
Write-Header "Part 5 -- Writing manifest.json"

# Build JSON manually to avoid encoding issues with ConvertTo-Json on older PS
$filesJson = ($ManifestEntries | ForEach-Object {
    $p = $_.path.Replace("\","/")
    "  {`"path`":`"$p`",`"sha256`":`"$($_.sha256)`",`"size`":$($_.size),`"label`":`"$($_.label)`"}"
}) -join ",`n"

$wordsJson = ($TARGET_WORDS | ForEach-Object { "`"$_`"" }) -join ","

$manifestJson = @"
{
  "generated_at": "$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')",
  "generator": "testkit/generate-test-content.ps1 v1.0.0",
  "heic_generated": $($heicGenerated.ToString().ToLower()),
  "spoken_word": {
    "script_file": "spoken-word/script.txt",
    "target_words": [$wordsJson],
    "wav_file": "spoken-word/speech.wav",
    "mp4_file": "spoken-word/spoken.mp4"
  },
  "files": [
$filesJson
  ]
}
"@

$manifestPath = "$CONTENT\manifest.json"
[System.IO.File]::WriteAllText($manifestPath, $manifestJson, [System.Text.Encoding]::UTF8)
Write-OK "manifest.json written ($($ManifestEntries.Count) file entries)"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
Write-Header "SUMMARY -- Files generated"
Write-Host ""
Write-Host "  testkit\content\" -ForegroundColor White
foreach ($e in $ManifestEntries) {
    $kb = [math]::Round($e.size / 1024, 1)
    Write-Host ("    {0,-55} {1,8} KB" -f $e.path, $kb) -ForegroundColor Gray
}
Write-Host ""
Write-Host "  Total: $($ManifestEntries.Count) files" -ForegroundColor Cyan
Write-Host ""
Write-Host "BURN INSTRUCTIONS" -ForegroundColor Yellow
Write-Host ("-" * 70) -ForegroundColor DarkGray
Write-Host ""
Write-Host "  [Test A3] DATA DVD ISO9660  -- burn content\data-disc\ as Data Disc"
Write-Host "    ImgBurn: Mode > Write Files/Folders > File System: ISO9660 > burn"
Write-Host ""
Write-Host "  [Test A4] DATA DVD Joliet   -- same folder, File System: Joliet"
Write-Host "    Tests long filenames and UCS-2 character handling"
Write-Host ""
Write-Host "  [Test A5] DATA DVD UDF      -- same folder, File System: UDF"
Write-Host "    Note: UDF VAT unsupported in Heirvo; expect gaps on packet-written discs"
Write-Host ""
Write-Host "  [Test C]  PHOTO DISC        -- burn content\photos\ as Data Disc"
Write-Host "    Tests gallery build + thumbnail generation + JPEG conversion"
Write-Host "    If HEIC-MISSING.txt exists, add an iPhone .heic file first"
Write-Host ""
Write-Host "  [Test D]  SPOKEN-WORD       -- burn content\spoken-word\ as Data Disc"
Write-Host "    Contains spoken.mp4. After Heirvo rescue, run verify-extraction.ps1"
$wordList = $TARGET_WORDS -join ", "
Write-Host "    Transcript must find: $wordList"
Write-Host ""
Write-Host "  [Test A1] DVD-VIDEO         -- read content\video-ts-source\HOW-TO-AUTHOR.txt"
Write-Host "    Requires DVDStyler + ImgBurn for the VIDEO_TS authoring step"
Write-Host ""
Write-Host "  [Test A7] AUDIO CD          -- burn content\spoken-word\speech.wav as Audio CD"
Write-Host "    ImgBurn: Mode > Write Audio CD > add speech.wav > burn"
Write-Host ""
Write-Host ("-" * 70) -ForegroundColor DarkGray
Write-Host ""
Write-Host "After each burn, run Heirvo rescue, then:" -ForegroundColor Cyan
Write-Host "  powershell -File .\testkit\verify-extraction.ps1" -ForegroundColor White
Write-Host "  Or: powershell -File .\testkit\verify-extraction.ps1 -TestMode spoken"
Write-Host ""
Write-Host "Content generation complete." -ForegroundColor Green
